tasks:
  - name: Install
    init: |
      pyenv install
      curl -sSL https://install.python-poetry.org/ | python -
      export PATH="/home/gitpod/.local/bin:$PATH"
      poetry install
  - name: Shell
    # The ~/.ssh directory will be removed between workspace runs
    # We store it on /workspace/ instead and link it
    # We also ensure that ssh-agent is added
    # Your own keys will need to be added through ssh-add or ~/.ssh/config
    before: |
      echo "Setting up SSH environment"
      rm -rf ~/.ssh
      mkdir -p /workspace/.ssh
      ln -sf /workspace/.ssh ~/.ssh
    command: eval $(ssh-agent -s)
    openMode: tab-after
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter